In [1]:
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
# read the train and test dataset
import sklearn
import pandas as pd
import re
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn import svm

In [2]:
data = pd.read_csv('Behavioral Biometrics/dataEditCopy.csv')

In [3]:
data.head()

,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
0,112,392,280,368,88,144,56,144,88,272,...,624,688,64,334.545455,225.454545,330.181818,105.333333,3744,1.633729e+12,1
1,104,376,272,392,120,248,128,208,80,144,...,776,832,56,386.909091,272.727273,382.545455,109.333333,4312,1.633729e+12,1
2,112,448,336,456,120,208,88,184,96,248,...,416,480,64,360.000000,246.545455,355.636364,109.333333,4024,1.633729e+12,1
3,112,488,376,480,104,168,64,160,96,456,...,968,1056,88,410.181818,295.272727,408.000000,112.666667,4600,1.633729e+12,1
4,96,360,264,344,80,184,104,192,88,216,...,408,472,64,328.000000,220.363636,325.090909,104.000000,3672,1.633729e+12,1

In [4]:
data.columns

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13',
       '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25',
       '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37',
       '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49',
       '50', '51', '52'],
      dtype='object')

In [5]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 52 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       115 non-null    int64
 1   2       115 non-null    int64
 2   3       115 non-null    int64
 3   4       115 non-null    int64
 4   5       115 non-null    int64
 5   6       115 non-null    int64
 6   7       115 non-null    int64
 7   8       115 non-null    int64
 8   9       115 non-null    int64
 9   10      115 non-null    int64
 10  11      115 non-null    int64
 11  12      115 non-null    int64
 12  13      115 non-null    int64
 13  14      115 non-null    int64
 14  15      115 non-null    int64
 15  16      115 non-null    int64
 16  17      115 non-null    int64
 17  18      115 non-null    int64
 18  19      115 non-null    int64
 19  20      115 non-null    int64
 20  21      115 non-null    int64
 21  22      115 non-null    int64
 22  23      115 non-null    int64
 23  24      115 non-null    int64
 24  25      115 non-null    int64
 25  26      115 non-null    int64
 26  27      115 non-null    int64
 27  28      115 non-null    int64
 28  29      115 non-null    int64
 29  30      115 non-null    int64
 30  31      115 non-null    int64
 31  32      115 non-null    int64
 32  33      115 non-null    int64
 33  34      115 non-null    int64
 34  35      115 non-null    int64
 35  36      115 non-null    int64
 36  37      115 non-null    int64
 37  38      115 non-null    int64
 38  39      115 non-null    int64
 39  40      115 non-null    int64
 40  41      115 non-null    int64
 41  42      115 non-null    int64
 42  43      115 non-null    int64
 43  44      115 non-null    int64
 44  45      115 non-null    int64
 45  46      115 non-null    float64
 46  47      115 non-null    float64
 47  48      115 non-null    float64
 48  49      115 non-null    float64
 49  50      115 non-null    int64
 50  51      115 non-null    float64
 51  52      115 non-null    int64
dtypes: float64(5), int64(47)
memory usage: 46.8 KB
None

In [6]:
data.describe()

,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
count,115.000000,115.00000,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000,...,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000,115.000000,1.150000e+02,115.000000
mean,94.026087,517.80000,423.278261,522.913043,99.634783,192.782609,93.147826,187.147826,94.000000,219.026087,...,423.643478,515.756522,92.113043,328.260870,213.283794,328.041897,113.030435,3631.747826,1.633608e+12,5.391304
std,29.593877,397.59607,401.578564,400.101600,30.339983,121.137937,117.967230,121.860810,33.786741,161.769625,...,439.158290,444.577004,41.358460,101.629919,90.805914,102.101614,32.768598,1212.022023,1.967202e+08,2.879741
min,47.000000,81.00000,1.000000,88.000000,47.000000,77.000000,-16.000000,48.000000,10.000000,64.000000,...,96.000000,160.000000,24.000000,166.545455,87.363636,168.000000,69.583333,759.000000,1.633127e+12,1.000000
25%,72.000000,287.50000,176.000000,280.500000,72.000000,128.000000,32.000000,112.000000,70.500000,120.000000,...,168.000000,251.500000,64.000000,238.954545,139.590909,238.545455,86.333333,2688.000000,1.633665e+12,3.000000
50%,88.000000,376.00000,280.000000,391.000000,96.000000,160.000000,61.000000,160.000000,88.000000,160.000000,...,240.000000,368.000000,80.000000,311.909091,199.454545,310.545455,108.666667,3504.000000,1.633668e+12,6.000000
75%,112.000000,561.00000,485.000000,572.000000,122.000000,216.000000,104.000000,208.000000,112.000000,252.000000,...,464.000000,556.000000,104.000000,395.227273,272.363636,397.090909,129.291667,4396.000000,1.633729e+12,8.000000
max,183.000000,2290.00000,2191.000000,2322.000000,160.000000,944.000000,848.000000,896.000000,208.000000,864.000000,...,2376.000000,2480.000000,216.000000,649.454545,534.545455,646.545455,214.750000,7224.000000,1.633730e+12,10.000000

In [7]:
test_data, train_data = sklearn.model_selection.train_test_split(data, train_size=.80, test_size=.20)
print(test_data.head())
print(train_data.head())

       1    2    3    4    5    6   7    8    9   10  ...   43   44   45  \
22    96  160   64  192  128  144  16  128  112  160  ...  144  256  112
94    74  164   90  157   67   98  31  107   76  118  ...  186  210   24
11   104  208  104  232  128  112 -16  104  120  144  ...  224  288   64
40    64  319  255  319   64  104  40  104   64  136  ...  160  240   80
114   64  640  576  640   64   80  16   80   64   80  ...  112  160   48

             46          47          48          49    50            51  52
22   237.090909  116.363636  238.545455  120.000000  2720  1.633729e+12   2
94   188.909091  109.090909  184.363636   75.166667  2102  1.633668e+12   8
11   240.727273  109.818182  237.090909  125.333333  2712  1.633127e+12   2
40   166.545455   95.181818  168.000000   72.083333  1912  1.633632e+12   4
114  240.000000  154.181818  238.545455   82.666667  2688  1.633729e+12  10

[5 rows x 52 columns]
       1     2     3     4    5    6    7    8    9   10  ...   43   44   45  \
57    72  1392  1320  1448  128  328  200  288   88  240  ...  144  208   64
84    70   141    71   149   78  102   24   93   69  122  ...  252  334   82
64    56   265   209   264   55  151   96  144   48  120  ...  137  201   64
70    88   728   640   752  112  168   56  160  104  304  ...  592  752  160
102  128   352   224   336  112  176   64  208  144  288  ...  384  592  208

             46          47          48          49    50            51  52
57   393.454545  301.727273  392.727273   89.416667  4392  1.633667e+12   6
84   210.636364  119.818182  211.727273   90.083333  2399  1.633668e+12   8
64   207.363636  137.272727  208.090909   69.583333  2345  1.633667e+12   6
70   441.454545  301.818182  448.000000  141.333333  5016  1.633668e+12   7
102  404.363636  218.454545  411.636364  187.750000  4656  1.633730e+12   9

[5 rows x 52 columns]

In [8]:
train_x = train_data.drop(columns=['52'],axis=1)
train_y = train_data['52']

In [9]:
test_x = test_data.drop(columns=['52'],axis=1)
test_y = test_data['52']

In [10]:
model = LogisticRegression()

In [11]:
model.fit(train_x,train_y)

LogisticRegression()

In [12]:
print('Coefficient of model :', model.coef_)

Coefficient of model : [[ 1.40890897e-23  1.07246381e-21  1.05837472e-21  1.07668593e-21
   1.83112123e-23  1.38898168e-22  1.20586956e-22  1.06917891e-22
  -1.36690650e-23  2.59590765e-23  3.96281415e-23  1.20856192e-22
   8.12280508e-23  4.14652468e-22  3.33424417e-22  2.85358188e-22
  -4.80662293e-23 -6.46721471e-22 -5.98655242e-22 -7.32690508e-22
  -1.34035266e-22 -4.21137272e-23  9.19215386e-23  1.72674480e-22
   8.07529409e-23  7.28160206e-22  6.47407265e-22  5.71088710e-22
  -7.63185549e-23  3.73637907e-23  1.13682346e-22  6.40760318e-23
  -4.96063138e-23  1.86722720e-22  2.36329034e-22  2.36231985e-22
  -9.70495983e-26  1.43079892e-22  1.43176942e-22  5.20281057e-23
  -9.11488362e-23 -2.02095952e-22 -1.10947116e-22 -2.35463403e-22
  -1.24516287e-22  1.68760816e-22  1.88629909e-22  1.56160328e-22
  -2.85896923e-23  1.73185269e-21 -1.02338623e-13]
 [-8.88312430e-24 -1.11387827e-21 -1.10499514e-21 -1.06362113e-21
   4.13740115e-23 -1.83254218e-22 -2.24628230e-22 -1.80713101e-22
   4.39151290e-23 -1.12029279e-22 -1.55944408e-22 -1.20703402e-22
   3.52410056e-23  1.23208936e-21  1.19684835e-21  1.18334936e-21
  -1.34989908e-23 -7.50095158e-22 -7.36596167e-22 -8.24453795e-22
  -8.78576279e-23 -8.80471300e-23 -1.89502100e-25 -3.44635086e-23
  -3.42740065e-23  7.23106205e-23  1.06584627e-22  2.83496824e-22
   1.76912197e-22 -3.88329024e-22 -5.65241221e-22 -5.80281860e-22
  -1.50406390e-23 -1.69955350e-22 -1.54914711e-22 -1.66473281e-22
  -1.15585707e-23  1.65599727e-23  2.81185434e-23  8.66247707e-23
   5.85062273e-23 -5.12534770e-22 -5.71040997e-22 -6.49476807e-22
  -7.84358099e-23 -1.81560295e-22 -1.98363533e-22 -1.87883267e-22
   8.86665012e-24 -2.07559906e-21 -1.02451431e-13]
 [-5.56950249e-23 -3.05341164e-22 -2.49646139e-22 -2.29147509e-22
   2.04986299e-23 -5.88008660e-23 -7.92994959e-23 -1.47065455e-22
  -6.77659590e-23 -3.17410983e-22 -2.49645024e-22 -3.13379011e-22
  -6.37339871e-23 -2.23131778e-22 -1.59397791e-22 -2.04069586e-22
  -4.46717957e-23 -4.05083337e-22 -3.60411541e-22 -5.41145890e-22
  -1.80734349e-22 -1.64999600e-22  1.57347490e-23  4.84592803e-23
   3.27245313e-23  3.08883094e-22  2.76158563e-22  2.44473486e-22
  -3.16850767e-23 -5.73338024e-23 -2.56487256e-23 -6.80793178e-24
   1.88407938e-23 -5.77269657e-23 -7.65677595e-23 -1.29251010e-22
  -5.26832500e-23 -1.41530552e-22 -8.88473018e-23 -1.45537866e-22
  -5.66905640e-23  2.07101505e-21  2.12770561e-21  2.03029175e-21
  -9.74138645e-23  5.89580996e-23  1.02739559e-22  5.51654778e-23
  -4.82508263e-23  5.51125231e-22 -5.26763480e-13]
 [-7.65703532e-23 -4.09431943e-22 -3.32861590e-22 -4.31104646e-22
  -9.82430558e-23 -1.40239493e-22 -4.19964368e-23 -1.23306069e-22
  -8.13096327e-23 -3.88422396e-22 -3.07112763e-22 -3.75526476e-22
  -6.84137135e-23 -1.17230465e-21 -1.10389094e-21 -1.19801934e-21
  -9.41284064e-23  1.34410643e-21  1.43823484e-21  1.14442231e-21
  -2.93812530e-22 -2.50772684e-22  4.30398465e-23 -2.58563550e-23
  -6.88962015e-23 -3.06253380e-22 -2.37357179e-22 -3.82756623e-22
  -1.45399444e-22 -4.80598788e-22 -3.35199344e-22 -3.74762996e-22
  -3.95636524e-23 -1.93113844e-22 -1.53550192e-22 -2.11221345e-22
  -5.76711531e-23 -1.20225854e-22 -6.25547010e-23 -1.43664063e-22
  -8.11093621e-23 -1.20352874e-21 -1.12241938e-21 -1.21388035e-21
  -9.14609768e-23 -3.01889577e-22 -2.01424349e-22 -3.03243270e-22
  -9.97148735e-23 -3.41224632e-21 -1.02262310e-13]
 [ 2.50322238e-22 -7.34004592e-22 -9.84326830e-22 -7.94828059e-22
   1.89498771e-22  3.35422074e-22  1.45923303e-22  4.21085255e-22
   2.75161952e-22 -1.83760211e-22 -4.58922163e-22 -3.08454010e-22
   1.50468153e-22  1.43402526e-21  1.28355711e-21  1.41073113e-21
   1.27174022e-22 -1.00206152e-21 -1.12923554e-21 -2.46192168e-22
   8.83043371e-22  6.09604005e-22 -2.73439365e-22 -7.47667895e-23
   1.98672576e-22 -5.62081011e-23 -2.54880677e-22 -1.79931255e-23
   2.36887551e-22  4.82127600e-22  2.45240048e-22  3.82432072e-22
   1.37192024e-22 -9.78890151e-23 -2.35081039e-22  3.47476681e-24
   2.38555806e-22  2.79599648e-22  4.10438419e-23  2.51574738e-22
   2.10530897e-22  1.80844019e-21  1.59790929e-21  1.98056732e-21
   3.82658028e-22  2.61390485e-22 -2.01927483e-24  2.73421012e-22
   2.73347116e-22  3.25795337e-21  1.45956822e-13]
 [-1.26201981e-22  3.64534682e-22  4.90736663e-22  3.83852430e-22
  -1.06884233e-22  1.15351021e-22  2.22235254e-22  6.44128074e-23
  -1.57822447e-22 -5.23636999e-22 -3.65814552e-22 -5.51910603e-22
  -1.86096051e-22 -8.58383024e-22 -6.72286974e-22 -8.90288289e-22
  -2.18001315e-22 -2.28670742e-22 -1.06694272e-23 -4.46034265e-22
  -4.35364838e-22 -2.70214652e-22  1.65150186e-22 -2.43577768e-23
  -1.89507963e-22 -5.33850150e-22 -3.44342187e-22 -5.36450594e-22
  -1.92108407e-22  6.78085077e-22  8.70193484e-22  6.46584339e-22
  -2.23609144e-22  2.36692187e-22  4.60301332e-22  1.79246836e-22
  -2.81054495e-22 -7.85059083e-23  2.02548587e-22  4.15528234e-24
  -1.98393305e-22 -2.34111335e-21 -2.14272005e-21 -2.33479490e-21
  -1.92074853e-22 -3.12701078e-22 -1.02242517e-22 -3.18689521e-22
  -2.08926586e-22 -3.63178671e-21  3.22063133e-13]
 [ 4.89234130e-23  1.21236121e-21  1.16343780e-21  1.18030890e-21
   1.68710991e-23  5.20248447e-23  3.51537456e-23  1.46319434e-22
   1.11165688e-22  2.05134749e-23 -9.06522134e-23 -2.50596792e-23
   6.55925343e-23  1.45072073e-22  7.94795386e-23  1.90828820e-22
   1.11349281e-22  9.97531871e-22  8.86182590e-22  1.20243187e-21
   3.16249278e-22  2.87365472e-22 -2.88838063e-23 -2.87331244e-23
   1.50681822e-25 -1.84241706e-22 -1.84392388e-22 -9.71155526e-23
   8.72768351e-23  1.26801936e-22  3.95251005e-23  1.07665743e-22
   6.81406421e-23 -1.44538293e-23 -8.25944714e-23  2.79289598e-23
   1.10523431e-22  8.82703248e-23 -2.22531063e-23  4.87369758e-23
   7.09900822e-23  1.53223282e-21  1.46124274e-21  1.57488967e-21
   1.13646928e-22  3.87588954e-22  2.96022321e-22  3.93472910e-22
   9.34066579e-23  4.37712542e-21  1.45957829e-13]
 [-1.29079293e-22 -1.80680144e-22 -5.16008514e-23 -1.39784024e-22
  -8.81831729e-23 -1.79553836e-22 -9.13706628e-23 -3.02419956e-22
  -2.11049293e-22  1.39539951e-21  1.60644881e-21  1.54550714e-21
  -6.09416677e-23 -1.98477578e-21 -1.92383411e-21 -1.79945869e-21
   1.24375419e-22 -8.32866186e-22 -9.57241605e-22 -1.09050979e-21
  -1.33268186e-22  1.46194876e-23  1.47887673e-22  3.60616162e-23
  -1.11826057e-22 -2.61963179e-22 -1.50137122e-22 -4.05542296e-22
  -2.55405174e-22 -3.20275031e-22 -6.48698570e-23 -1.41746213e-22
  -7.68763555e-23  2.20678749e-24  7.90831430e-23 -7.25012944e-23
  -1.51584437e-22 -2.98605675e-22 -1.47021237e-22 -2.05874566e-22
  -5.88533289e-23 -1.34850927e-21 -1.28965594e-21 -1.29615695e-21
  -6.50101309e-24 -3.63182119e-22 -2.58391978e-22 -3.52038639e-22
  -9.65993799e-23 -4.00150432e-21  3.22063549e-13]
 [ 8.30950354e-23  9.39764078e-23  1.08813724e-23  1.76381102e-23
   6.75673778e-24 -7.98476962e-23 -8.66044340e-23  1.47691934e-23
   1.01373627e-22  8.33878039e-23 -1.79858235e-23  2.86698517e-23
   4.66556752e-23  1.01275607e-21  9.66100395e-22  1.02156841e-21
   5.54680152e-23  1.52386011e-21  1.46839210e-21  1.53417224e-21
   6.57801469e-23 -9.54411727e-23 -1.61221320e-22 -6.90178216e-23
   9.22034979e-23  2.33162596e-22  1.40959098e-22  3.40799171e-22
   1.99840073e-22 -7.78417577e-23 -2.77681831e-22 -9.71591857e-23
   1.80522645e-22  1.07517309e-22 -7.30053363e-23  1.32564383e-22
   2.05569719e-22  1.11358151e-22 -9.42115680e-23  5.19566217e-23
   1.46168190e-22  1.96094028e-22  4.99258387e-23  1.44023688e-22
   9.40978489e-23  2.82634714e-22  1.75049863e-22  2.83634970e-22
   1.06460934e-22  3.20307970e-21 -1.02225487e-13]]

In [13]:
predict_train = model.predict(train_x)
print('Target on train data',predict_train)

Target on train data [8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]

In [14]:
accuracy_train = accuracy_score(train_y,predict_train)
print('accuracy_score on train dataset : ', accuracy_train)

accuracy_score on train dataset :  0.17391304347826086

In [15]:
predict_test = model.predict(test_x)
print('Target on test data',predict_test)

Target on test data [8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8
 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8
 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]

In [ ]:
X = data.drop(columns=['52'],axis=1)
y = data['52']
clf = svm.SVC(kernel='linear', C=1)
scores = cross_val_score(clf, X, y, cv=5)
print(scores, scores.mean())